# Generated by Django 5.1.15 on 2026-05-10 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_limite", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_path", models.CharField(max_length=500)),
                ("nombre_original", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("tamaño_bytes", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="planes.actividad",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_subidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_trabajo",
                        to="acciones.accion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actividad",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="planes.plantrabajo",
            ),
        ),
        migrations.AddIndex(
            model_name="plantrabajo",
            index=models.Index(fields=["accion"], name="planes_plan_accion_idx"),
        ),
        migrations.AddIndex(
            model_name="actividad",
            index=models.Index(fields=["plan"], name="planes_act_plan_idx"),
        ),
        migrations.AddIndex(
            model_name="actividad",
            index=models.Index(
                fields=["fecha_limite"], name="planes_act_fecha_limite_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividad",
            index=models.Index(fields=["estado"], name="planes_act_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="actividad",
            index=models.Index(
                fields=["responsable"], name="planes_act_responsable_idx"
            ),
        ),
    ]
