# Generated by Django 5.1.15 on 2026-05-09 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagramaIshikawa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CausaRaiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("metodo", "Método"),
                            ("maquina", "Máquina"),
                            ("material", "Material"),
                            ("mano_de_obra", "Mano de Obra"),
                            ("medicion", "Medición"),
                            ("medio_ambiente", "Medio Ambiente"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagrama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="causas",
                        to="issues.diagramaishikawa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incidente", "Incidente"),
                            ("casi_incidente", "Casi Incidente"),
                            ("reunion_seguridad", "Reunión de Seguridad"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descripcion", models.TextField()),
                ("fecha_evento", models.DateField()),
                ("area", models.CharField(max_length=200)),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_analisis", "En Análisis"),
                            ("acciones_generadas", "Acciones Generadas"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reportado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues_reportados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialTransicionIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(max_length=30)),
                ("estado_nuevo", models.CharField(max_length=30)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True, default="")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="diagramaishikawa",
            name="issue",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ishikawa",
                to="issues.issue",
            ),
        ),
        migrations.CreateModel(
            name="SubCausa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "causa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcausas",
                        to="issues.causaraiz",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["estado"], name="issues_issu_estado_67f980_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["fecha_evento"], name="issues_issu_fecha_e_dfef3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["reportado_por"], name="issues_issu_reporta_9d0602_idx"
            ),
        ),
    ]
