# Generated by Django 5.1.15 on 2026-05-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-created_at"]},
        ),
    ]
