# Generated by Django 5.1.15 on 2026-05-09 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0002_alter_issue_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("correctiva", "Correctiva"),
                            ("preventiva", "Preventiva"),
                            ("mejora", "De Mejora"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resultado_esperado", models.TextField()),
                ("fecha_limite", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En Proceso"),
                            ("cerrado", "Cerrado"),
                            ("verificado", "Verificado"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acciones",
                        to="issues.issue",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acciones_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(max_length=20)),
                ("estado_nuevo", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True, default="")),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="acciones.accion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="accion",
            index=models.Index(fields=["estado"], name="acciones_ac_estado_bbf2f8_idx"),
        ),
        migrations.AddIndex(
            model_name="accion",
            index=models.Index(
                fields=["fecha_limite"], name="acciones_ac_fecha_l_d8c92d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accion",
            index=models.Index(
                fields=["responsable"], name="acciones_ac_respons_ca0bfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accion",
            index=models.Index(fields=["issue"], name="acciones_ac_issue_i_b8e0f4_idx"),
        ),
    ]
